# Generated by Django 4.1.2 on 2022-10-13 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_user_mbti_user_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_img',
        ),
    ]
