# Generated by Django 4.1.2 on 2022-10-14 01:27

from django.db import migrations

def user_to_profile(apps, schema_editor):
    User = apps.get_model('board', 'User')
    Profile = apps.get_model('board', 'Profile')
    for user in User.objects.all():
        Profile.objects.create(
            nickname = user.nickname,
            profile_pic = user.profile_pic,
            intro = user.intro,
            user = user,
        )

class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_profile'),
    ]

    operations = [
        migrations.RunPython(user_to_profile),
    ]
