# Generated by Django 4.1.2 on 2022-10-14 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_migrate_profile_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
