# Generated by Django 4.1.2 on 2022-10-14 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-dt_created']},
        ),
    ]
