# Generated by Django 4.1.2 on 2022-11-09 07:14

import board.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_change_reverse_relationships'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mail',
            field=models.CharField(error_messages={'unique': '이미 사용중인 이메일입니다.'}, max_length=60, null=True, unique=True, validators=[board.validators.validate_email]),
        ),
    ]
